### ISSUE TITLE
Where did my account go?

### ISSUE THREAD

**Issue by SLStewart54** [eugene-khyst/artistassistapp#19]
### Discussed in https://github.com/eugene-khyst/artistassistapp/discussions/17

<div type='discussions-op-text'>

<sup>Originally posted by **SLStewart54** July 31, 2024</sup>
Love AAA, I’ve been using it for months. Now when I open the app, I’m sent to the “Start” page. I can’t find my saved data. Where are my colors, photos, etc.? I do not want to start over. I have color sets for specific photos saved and need them. I’m on an iPad, OS 17.5.1.</div>

**Comment by eugene-khyst** [comment]
ArtistAssistApp is still available at [app.artistassistapp.com](http://app.artistassistapp.com/) and now can even be installed on your device for offline access.
The latest features required changing the way the app stores data. Thus, color sets, photos and color mixtures were cleared.
In this article I described the latest new features, technical challenges and how I solved them: https://dev.to/eugene-khyst/artistassistapp-is-now-available-offline-and-has-other-cool-new-features-1ke6

You can create you color set once again, it's even simpler now. I'm sorry for the inconvenience.

If you have problems with saving color sets and photos:

- Make sure you don't use the web browser in incognito (private) mode because in this mode browser clears all website data after closing the window. 
- Make sure you don't have enabled any browser extensions that blocks website data.
- Don't forget to press Save & proceed button on the Color set tab after you finished choosing your brands and colors.
- Consider trying different web browser, e.g. Google Chrome or Firefox instead of Safari.

**Comment by SLStewart54** [comment]
Thank you Eugene, This reply answered all my questions and fixed my
problem. Now I can use the app with confidence.

I'm looking forward to using it in future paintings.
